# 로컬 및 서비스 목적이 없으므로 yml파일도 올립니다.
spring:
  datasource:
    hikari:
      connection-timeout: 5000
      maximum-pool-size: 10
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3307/webdb
    username: elicer
    password: devpassword
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  servlet:
    multipart:
      enabled: true
      location: C:\\upload
      max-request-size: 30MB
      max-file-size: 10MB

org:
  ruu:
    bootthymeleafjpa:
      upload:
        path: C:\\upload


logging:
  level:
    org.ruu.bootthymeleafjpa: info
    org.ruu: debug
    org.springframework.security: trace






